name: Pull Request on Branch Push
on:
  push:
    branches:
      - feature/*
jobs:
  auto-pull-request:
    name: PullRequestAction
    runs-on: ubuntu-latest
    steps:
      - name: pull-request-action
        uses: vsoch/pull-request-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH_PREFIX: "feature/"
          PULL_REQUEST_BRANCH: "main"
          PULL_REQUEST_UPDATE: true 
